##  对高频彩11选5中奖结果进行统计分析

In [548]:
import requests
from  bs4 import BeautifulSoup
import os
import lxml
import numpy as np

#获取url下的页面内容，返回soup对象
def get_page(url):
    responce = requests.get(url)
    soup = BeautifulSoup(responce.text,'lxml')
    return soup

In [549]:
#获取网页数据
urlcount=1000
url ="http://chart.icaile.com/chart/yn/?top="+str(urlcount)
soup = get_page(url)

In [550]:
#打印数据统计结果
def printf(b,urlcount):
    #大小排序
    b.sort(axis=1)
    print("期号：\t\t\t开奖号：\t出现次数:")
    #统计出现次数
    for a in range(urlcount):
        count = 0
        numb = b[a]
        for i in b:
            m=(i==numb)
            flag = False
            for j in m:
                if(j):
                    flag=True
                else:
                    flag=False
                    break
            if(flag==True):
                 count=count+1
        print(day_list[a]+"\t",numb,"\t\t",count)
        
#存储日期
day_list=[]
day = soup.find_all('',{"class":"rline period"})
for td in day:
    day_list.append(td.get_text())
    
#存储前三个号
first_numb_list = []
second_numb_list = []
thrith_numb_list = []
i=0
three_numb = soup.find_all("",{"class":" weak lotteryNumber bold myColor1"})
for td in three_numb:
    X=int(td.get_text())
   # print(X)
    if(0==i):
        first_numb_list.append(X)
        i=i+1
    elif(1==i):
        second_numb_list.append(X)
        i=i+1
    elif(2==i):
        thrith_numb_list.append(X)
        i=0
    else:
        print("出错！")
        break

#存储第四个号
fourth_numb = soup.find_all('',{"class":" weak lotteryNumber bold myColor2"})
fourth_numb_list = []
for td in fourth_numb:
    X=int(td.get_text())
    fourth_numb_list.append(X)
    
#存储第五个号
fif_numb = soup.find_all('',{"class":"rline weak lotteryNumber bold myColor2"})
fif_numb_list = []
for td in fif_numb:
    X=int(td.get_text())
    fif_numb_list.append(X)

#数据处理
x=np.array([[ 9,2 ,5,7,6],[6,5,9,11,3]])
for i in range(urlcount):
    x=np.append(x,[[first_numb_list[i],second_numb_list[i],thrith_numb_list[i],fourth_numb_list[i],fif_numb_list[i]]],axis = 0)

#去除前两个数据
z=np.delete(x,0,axis = 0)
z=np.delete(z,0,axis = 0)
numb_list=z[::-1].copy()

In [551]:
day_list = day_list[::-1].copy()
z = z[::-1].copy()

In [552]:
#打印最新的数据
m=0
print("期号\t\t开奖号")
for i in z:
    print(day_list[m]+"\t",i)
    m=m+1

期号		开奖号
190320-36	 [ 2  3  8  1 10]
190320-35	 [ 8 11  2  3  5]
190320-34	 [ 9 10  2  7  8]
190320-33	 [ 2 10  3  9  5]
190320-32	 [5 4 7 3 8]
190320-31	 [10  9  1  4  8]
190320-30	 [ 9 10 11  8  3]
190320-29	 [ 9  7  4  5 11]
190320-28	 [11  8  1  3  9]
190320-27	 [8 5 2 7 4]
190320-26	 [ 3 10  7  2  6]
190320-25	 [ 6  4  8  2 10]
190320-24	 [ 3 11  9  8 10]
190320-23	 [5 4 9 3 2]
190320-22	 [7 1 5 3 6]
190320-21	 [1 2 7 4 5]
190320-20	 [ 5 10  2  8  4]
190320-19	 [1 6 9 5 8]
190320-18	 [ 8  5  3  4 10]
190320-17	 [ 8  5  7  6 11]
190320-16	 [ 6 11  9  7  1]
190320-15	 [8 9 5 7 1]
190320-14	 [3 1 7 5 6]
190320-13	 [ 1  7 11  4  3]
190320-12	 [ 2  4  3  7 10]
190320-11	 [3 9 8 6 1]
190320-10	 [2 6 7 5 8]
190320-09	 [ 5  2  8  7 11]
190320-08	 [9 8 2 7 1]
190320-07	 [ 3 10  9  8  7]
190320-06	 [2 9 6 7 8]
190320-05	 [3 6 4 7 8]
190320-04	 [ 1  6 10  2  8]
190320-03	 [ 2  1 10  5  9]
190320-02	 [ 5 10 11  9  7]
190320-01	 [2 4 3 7 8]
190319-42	 [ 1  3 11  4  7]
190319-41	 [ 4  5 10  9  6

190312-18	 [11  7  6  5  2]
190312-17	 [10  3  2  1  8]
190312-16	 [10  8  4  3  6]
190312-15	 [10  5  6  7  8]
190312-14	 [ 3  8 11 10  5]
190312-13	 [ 5  3  7 11  2]
190312-12	 [ 6  7  2  4 10]
190312-11	 [ 4  9  3 10  6]
190312-10	 [4 7 9 3 8]
190312-09	 [ 8  9 10  5  2]
190312-08	 [ 5  2 11  3 10]
190312-07	 [11  5  2 10  6]
190312-06	 [ 8  9  5 11  6]
190312-05	 [1 5 6 7 8]
190312-04	 [9 8 2 3 5]
190312-03	 [ 1 11  5  9  2]
190312-02	 [ 4 11  2  8  9]
190312-01	 [ 9 10  2  8  1]
190311-42	 [ 4  3  7 10  8]
190311-41	 [ 4  5  9 11  7]
190311-40	 [ 5 10  3  1  9]
190311-39	 [10  6  1  2  4]
190311-38	 [ 8 11  2  7  6]
190311-37	 [ 6  1  3  2 11]
190311-36	 [11 10  2  6  1]
190311-35	 [10 11  8  1  5]
190311-34	 [ 6  1 10  7  4]
190311-33	 [ 5  9  4  6 10]
190311-32	 [10  1 11  3  5]
190311-31	 [2 4 8 1 3]
190311-30	 [ 5 10  1  8  4]
190311-29	 [ 5 10  2  7  6]
190311-28	 [ 7  8  1 11  6]
190311-27	 [ 9 11  6  1  7]
190311-26	 [ 6  4 10  5  9]
190311-25	 [ 7  2  5  9 11]
190311-24	 [

190227-15	 [11  7  1 10  5]
190227-14	 [ 2  8  9 11  4]
190227-13	 [8 7 9 1 5]
190227-12	 [10  7 11  9  2]
190227-11	 [ 6  2  5  7 10]
190227-10	 [8 6 4 7 5]
190227-09	 [ 9  7 10 11  8]
190227-08	 [ 2  4  7 10  8]
190227-07	 [5 1 7 9 3]
190227-06	 [ 8  2 10  1  7]
190227-05	 [8 2 7 1 3]
190227-04	 [ 6  7  5 11  9]
190227-03	 [ 2  5  3  9 10]
190227-02	 [ 4  7  9  3 11]
190227-01	 [ 4  3 10  1  6]
190226-42	 [5 1 9 7 3]
190226-41	 [1 6 3 5 7]
190226-40	 [2 7 1 5 3]
190226-39	 [ 8  2 11  9  3]
190226-38	 [6 3 1 8 4]
190226-37	 [ 4  3  1 11  9]
190226-36	 [2 4 9 3 6]
190226-35	 [8 3 7 2 6]
190226-34	 [ 1  3  9 10 11]
190226-33	 [ 8  5 11  2  3]
190226-32	 [10  7 11  6  1]
190226-31	 [11  3  4  8  9]
190226-30	 [1 6 4 3 2]
190226-29	 [ 3  7  5  4 10]
190226-28	 [10  8  6  7  1]
190226-27	 [ 1  5  7 10  4]
190226-26	 [ 9  7 10  2  6]
190226-25	 [10  6 11  7  8]
190226-24	 [10  7  3  9  1]
190226-23	 [ 3 11  1 10  2]
190226-22	 [11  3  2  1  5]
190226-21	 [ 6  3  5 11  4]
190226-20	 [ 5 10  

In [553]:
#输出统计结果
printf(numb_list,urlcount)

期号：			开奖号：	出现次数:
190320-36	 [ 1  2  3  8 10] 		 3
190320-35	 [ 2  3  5  8 11] 		 5
190320-34	 [ 2  7  8  9 10] 		 2
190320-33	 [ 2  3  5  9 10] 		 4
190320-32	 [3 4 5 7 8] 		 3
190320-31	 [ 1  4  8  9 10] 		 2
190320-30	 [ 3  8  9 10 11] 		 5
190320-29	 [ 4  5  7  9 11] 		 2
190320-28	 [ 1  3  8  9 11] 		 2
190320-27	 [2 4 5 7 8] 		 1
190320-26	 [ 2  3  6  7 10] 		 1
190320-25	 [ 2  4  6  8 10] 		 1
190320-24	 [ 3  8  9 10 11] 		 5
190320-23	 [2 3 4 5 9] 		 3
190320-22	 [1 3 5 6 7] 		 5
190320-21	 [1 2 4 5 7] 		 5
190320-20	 [ 2  4  5  8 10] 		 3
190320-19	 [1 5 6 8 9] 		 5
190320-18	 [ 3  4  5  8 10] 		 1
190320-17	 [ 5  6  7  8 11] 		 3
190320-16	 [ 1  6  7  9 11] 		 6
190320-15	 [1 5 7 8 9] 		 6
190320-14	 [1 3 5 6 7] 		 5
190320-13	 [ 1  3  4  7 11] 		 5
190320-12	 [ 2  3  4  7 10] 		 4
190320-11	 [1 3 6 8 9] 		 4
190320-10	 [2 5 6 7 8] 		 3
190320-09	 [ 2  5  7  8 11] 		 1
190320-08	 [1 2 7 8 9] 		 1
190320-07	 [ 3  7  8  9 10] 		 2
190320-06	 [2 6 7 8 9] 		 2
190320-05	 [3 4 6 7 

190313-31	 [ 2  3  7  8 10] 		 4
190313-30	 [ 1  3  7 10 11] 		 2
190313-29	 [ 1  5  6  7 10] 		 1
190313-28	 [2 4 5 6 8] 		 3
190313-27	 [ 1  2  8  9 11] 		 2
190313-26	 [ 1  4  5  8 10] 		 3
190313-25	 [ 3  4  5  8 11] 		 5
190313-24	 [ 6  8  9 10 11] 		 1
190313-23	 [ 1  3  5  8 11] 		 3
190313-22	 [1 2 4 6 9] 		 4
190313-21	 [ 5  8  9 10 11] 		 2
190313-20	 [ 1  6  7  9 11] 		 6
190313-19	 [ 1  5  6  9 11] 		 2
190313-18	 [1 3 6 7 8] 		 5
190313-17	 [1 2 4 5 9] 		 3
190313-16	 [ 2  3  4  8 11] 		 1
190313-15	 [ 1  5  7  9 10] 		 5
190313-14	 [ 3  4  5  6 10] 		 3
190313-13	 [ 1  4  6 10 11] 		 5
190313-12	 [ 4  5  6  7 11] 		 4
190313-11	 [ 3  4  8  9 10] 		 3
190313-10	 [1 3 4 7 8] 		 3
190313-09	 [ 2  3  4  6 10] 		 2
190313-08	 [4 5 6 8 9] 		 2
190313-07	 [2 3 4 6 7] 		 6
190313-06	 [ 1  3  5  9 11] 		 3
190313-05	 [4 5 7 8 9] 		 4
190313-04	 [ 2  6  7  9 10] 		 3
190313-03	 [ 1  2  4 10 11] 		 3
190313-02	 [ 4  6  7  9 11] 		 1
190313-01	 [ 1  4  5 10 11] 		 4
190312-42	 [1 2 3

190305-12	 [1 3 5 6 7] 		 5
190305-11	 [ 1  2  7  9 11] 		 1
190305-10	 [ 3  5  6  7 11] 		 1
190305-09	 [ 1  3  4  6 10] 		 2
190305-08	 [ 1  3  7  8 11] 		 3
190305-07	 [ 1  4  7  8 10] 		 3
190305-06	 [3 5 6 8 9] 		 1
190305-05	 [ 1  3  4  9 10] 		 6
190305-04	 [ 2  4  5  8 11] 		 3
190305-03	 [ 3  6  7  9 11] 		 3
190305-02	 [ 4  6  8  9 10] 		 4
190305-01	 [ 3  4  6  8 10] 		 4
190304-42	 [ 2  7  9 10 11] 		 2
190304-41	 [ 1  3  8 10 11] 		 4
190304-40	 [1 4 5 8 9] 		 1
190304-39	 [ 1  2  7  9 10] 		 3
190304-38	 [ 4  8  9 10 11] 		 3
190304-37	 [ 3  5  7 10 11] 		 1
190304-36	 [ 1  3  4  9 10] 		 6
190304-35	 [2 6 7 8 9] 		 2
190304-34	 [ 1  5  7  9 10] 		 5
190304-33	 [ 2  5  6  9 11] 		 4
190304-32	 [ 2  4  7  9 11] 		 3
190304-31	 [ 6  7  8 10 11] 		 3
190304-30	 [ 1  4  5  9 10] 		 3
190304-29	 [ 1  3  6  8 10] 		 3
190304-28	 [ 4  5  6  8 10] 		 2
190304-27	 [ 2  5  6  7 11] 		 4
190304-26	 [ 1  5  7 10 11] 		 2
190304-25	 [ 2  5  9 10 11] 		 2
190304-24	 [1 3 4 5 7] 		 1
19

190226-18	 [ 2  4  7  9 10] 		 2
190226-17	 [1 3 4 5 8] 		 3
190226-16	 [ 1  2  7 10 11] 		 5
190226-15	 [ 1  4  8 10 11] 		 2
190226-14	 [ 1  3  4  8 11] 		 2
190226-13	 [ 1  4  7  9 11] 		 3
190226-12	 [ 1  3  4  9 10] 		 6
190226-11	 [ 1  2  8 10 11] 		 1
190226-10	 [ 4  6  7 10 11] 		 3
190226-09	 [2 3 4 6 7] 		 6
190226-08	 [1 3 4 6 7] 		 4
190226-07	 [ 2  4  6  8 11] 		 1
190226-06	 [ 2  3  4  9 11] 		 5
190226-05	 [ 1  4  5  9 11] 		 3
190226-04	 [1 2 3 5 7] 		 6
190226-03	 [ 1  2  7 10 11] 		 5
190226-02	 [ 1  2  3  9 10] 		 3
190226-01	 [1 2 6 7 9] 		 4
190225-42	 [2 3 5 6 8] 		 3
190225-41	 [2 3 5 6 9] 		 2
190225-40	 [1 2 3 4 8] 		 2
190225-39	 [2 3 5 6 9] 		 2
190225-38	 [ 1  3  5  7 11] 		 5
190225-37	 [ 5  6  7  9 11] 		 7
190225-36	 [1 3 5 6 7] 		 5
190225-35	 [ 4  8  9 10 11] 		 3
190225-34	 [ 3  6  7  9 10] 		 3
190225-33	 [ 1  2  3  7 10] 		 2
190225-32	 [2 3 4 7 8] 		 3
190225-31	 [ 1  3  5 10 11] 		 4
190225-30	 [ 3  6  9 10 11] 		 1
190225-29	 [3 4 6 7 9] 		 5
1902

In [554]:
c =z.copy()

In [555]:
c.sort(axis=1)

In [556]:
num2 = np.array([2,5,])
d[:2]==num2

array([False, False])

In [557]:
num1 = np.array([3])
counts = 0
print("任1选号: \n",num,"\n\n出现期号：\t")
#统计出现次数
K=0
for i in z:
    if(i[0]==num1):
        print(day_list[K])
        counts=counts+1
    K=K+1
win = (counts / urlcount)*100
print("\n出现次数：\n",counts,"\n中奖率：",win,"%")
print("盈亏：",counts * 13 - urlcount * 2)

任1选号: 
 [ 2  5  6  8 10] 

出现期号：	
190320-26
190320-24
190320-14
190320-11
190320-07
190320-05
190319-37
190319-23
190319-19
190319-05
190319-01
190318-42
190318-20
190318-19
190317-29
190317-27
190317-02
190316-23
190316-10
190315-40
190315-38
190315-07
190314-33
190314-32
190314-04
190313-25
190313-14
190313-10
190312-32
190312-29
190312-22
190312-14
190311-24
190311-08
190310-35
190310-33
190310-31
190310-20
190310-09
190309-10
190308-40
190308-34
190308-20
190308-04
190307-06
190306-40
190306-37
190305-39
190305-30
190305-23
190305-18
190305-10
190305-01
190304-18
190304-04
190303-26
190303-02
190302-27
190302-24
190302-23
190302-21
190301-40
190301-32
190301-14
190228-42
190228-33
190228-02
190227-42
190227-34
190227-26
190227-25
190226-29
190226-23
190225-33
190225-27

出现次数：
 75 
中奖率： 7.5 %
盈亏： -1025


In [558]:
def fun2(num2,c): 
    #print("出现期号：")
    #统计出现次数
    counts = 0
    K=0
    for i in c:
        if(num2[0] in i):
            if(num2[1] in i):
               # print(day_list[K])
                counts=counts+1
        #K=K+1
    win = (counts / urlcount)*100
    print("\n出现次数：\n",counts,"\n中奖率：",win,"%")
    return counts
def fun22(num2,c): 
    print("出现期号：")
    #统计出现次数
    counts = 0
    K=0
    for i in c:
        if(num2[0]== i[0]):
            if(num2[1] == i[1]):
                print(day_list[K])
                counts=counts+1
        K=K+1
    win = (counts / urlcount)*100
    print("\n出现次数：\n",counts,"\n中奖率：",win,"%")
    return counts

In [559]:
num2 = np.array([3,4])
print("任2选号: \n",num2)
print("盈亏：",fun2(num2,c) * 6 - urlcount * 2)

任2选号: 
 [3 4]

出现次数：
 196 
中奖率： 19.6 %
盈亏： -824


In [560]:
#num22 = np.array([1,3])
num22 = np.array([3,6])
print("前2直选号: \n",num2)
print("盈亏：",fun22(num22,z) * 130 - urlcount * 2)

前2直选号: 
 [3 4]
出现期号：
190320-05
190318-42
190315-40
190314-04
190313-14
190310-09
190305-39
190305-01

出现次数：
 8 
中奖率： 0.8 %
盈亏： -960


In [561]:
num3 = np.array([1,3,7])
counts = 0
print("任3选号: \n",num3)
print("出现期号：")
#统计出现次数
K=0
for i in c:
    if(num3[0] in i):
        if(num3[1] in i):
            if(num3[2] in i):
                print(day_list[K])
                counts=counts+1
    K=K+1
win = (counts / urlcount)*100
print("\n出现次数：\n",counts,"\n中奖率：",win,"%")
print("盈亏：",counts * 19 - urlcount * 2)

任3选号: 
 [1 3 7]
出现期号：
190320-22
190320-14
190320-13
190319-42
190319-19
190318-24
190318-19
190318-16
190316-39
190316-28
190316-23
190315-30
190315-08
190315-07
190315-04
190314-16
190314-05
190313-33
190313-32
190313-30
190313-18
190313-10
190312-42
190312-32
190312-26
190312-24
190311-07
190310-33
190310-01
190309-25
190309-17
190309-14
190308-10
190307-26
190307-18
190306-12
190306-06
190305-23
190305-17
190305-15
190305-12
190305-08
190304-24
190303-32
190303-29
190303-26
190303-02
190303-01
190302-33
190302-26
190302-03
190301-24
190301-16
190301-14
190228-30
190228-28
190228-04
190228-02
190227-39
190227-28
190227-07
190227-05
190226-42
190226-41
190226-40
190226-24
190226-08
190226-04
190225-38
190225-36
190225-33
190225-20
190225-09

出现次数：
 73 
中奖率： 7.3 %
盈亏： -613


In [562]:
num33 = np.array([1,2,5])
counts = 0
print("前3直选号: \n",num3)
#print("出现期号：")
#统计出现次数
K=0
for i in z:
    if(num33[0] == i[0]):
        if(num33[1] == i[1]):
            if(num33[2] == i[2]):
                #print(day_list[K])
                counts=counts+1
    #K=K+1
win = (counts / urlcount)*100
print("\n出现次数：\n",counts,"\n中奖率：",win,"%")
print("盈亏：",counts * 1170 - urlcount * 2)

前3直选号: 
 [1 3 7]

出现次数：
 0 
中奖率： 0.0 %
盈亏： -2000


In [563]:
num4 = np.array([2,4,8,10])
#num4 = np.array([1,3,5,7])
#num4 = np.array([2,4,7,11])
#num4 = np.array([1,4,7,11])
counts = 0
print("任4选号: \n",num4)
print("出现期号：")
#统计出现次数
K=0
for i in c:
    if(num4[0] in i):
        if(num4[1] in i):
            if(num4[2] in i):
                if(num4[3] in i):
                    print(day_list[K],"\t",c[K])
                    counts=counts+1
    K=K+1
win = (counts / urlcount)*100
print("\n出现次数：\n",counts,"\n中奖率：",win,"%")
print("盈亏：",counts * 78 - urlcount * 2)

任4选号: 
 [ 2  4  8 10]
出现期号：
190320-25 	 [ 2  4  6  8 10]
190320-20 	 [ 2  4  5  8 10]
190319-25 	 [ 1  2  4  8 10]
190315-01 	 [ 2  4  7  8 10]
190314-28 	 [ 1  2  4  8 10]
190314-02 	 [ 2  4  5  8 10]
190310-24 	 [ 2  4  8 10 11]
190310-19 	 [ 2  4  7  8 10]
190309-21 	 [ 2  4  5  8 10]
190309-13 	 [ 2  4  8  9 10]
190308-21 	 [ 1  2  4  8 10]
190302-41 	 [ 2  3  4  8 10]
190228-27 	 [ 1  2  4  8 10]
190227-08 	 [ 2  4  7  8 10]

出现次数：
 14 
中奖率： 1.4000000000000001 %
盈亏： -908


In [564]:
def function(nums,c):
    counts = 0
    print("\n出现期号：\t")
    #统计出现次数
    K=0
    for i in c:
        if(i[0] in nums):
            if(i[1] in nums):
                if(i[2] in nums):
                    if(i[3] in nums):
                        if(i[4] in nums):
                            print(day_list[K])
                            counts=counts+1
        K=K+1
    win = (counts / urlcount)*100
    print("\n出现次数：\n",counts,"\n中奖率：",win,"%")
    return counts

In [565]:
num5 = np.array([2,5,6,9,11])
print("任5选号: \n",num5)
print("盈亏：",function(num5,c)*540 - urlcount*2)

任5选号: 
 [ 2  5  6  9 11]

出现期号：	
190317-18
190308-31
190304-33
190304-12

出现次数：
 4 
中奖率： 0.4 %
盈亏： 160


In [566]:
num6 = np.array([1,3,5,6,7,10])
print("任6选号: \n",num6)
print("盈亏：",function(num6,c)*90 - urlcount*2)

任6选号: 
 [ 1  3  5  6  7 10]

出现期号：	
190320-22
190320-14
190318-22
190316-40
190313-29
190309-25
190306-01
190305-23
190305-12
190301-42
190226-41
190225-36

出现次数：
 12 
中奖率： 1.2 %
盈亏： -920


In [567]:
num7 = np.array([1,3,5,7,10,11])
print("任7选号: \n",num7)
print("盈亏：",function(num7,c)*26 - urlcount*2)


任7选号: 
 [ 1  3  5  7 10 11]

出现期号：	
190318-36
190318-16
190315-33
190313-33
190313-30
190312-26
190311-32
190307-18
190304-37
190304-26
190303-01
190227-15
190225-38
190225-31

出现次数：
 14 
中奖率： 1.4000000000000001 %
盈亏： -1636


In [568]:
#num8 = np.array([1,2,4,6,7,8,9,11])
num8 = np.array([1,2,5,6,7,8,10,11])
print("任8选号: \n",num8)
print("盈亏：",function(num8,c)*9 - urlcount*2)

任8选号: 
 [ 1  2  5  6  7  8 10 11]

出现期号：	
190320-17
190320-10
190320-09
190320-04
190319-27
190318-35
190318-33
190318-28
190318-18
190318-06
190317-35
190317-28
190317-24
190317-12
190317-09
190316-37
190316-26
190316-22
190316-16
190316-08
190316-01
190315-25
190315-23
190315-20
190315-12
190314-26
190314-15
190314-11
190313-29
190312-37
190312-34
190312-30
190312-18
190312-15
190312-07
190312-05
190311-38
190311-36
190311-35
190311-29
190311-28
190311-23
190311-06
190310-41
190310-40
190310-37
190310-25
190310-14
190310-13
190310-05
190309-37
190309-29
190309-26
190309-19
190309-12
190309-11
190308-38
190308-33
190308-22
190307-42
190307-36
190307-29
190307-23
190306-39
190306-34
190306-31
190306-27
190306-23
190306-19
190306-17
190306-07
190305-37
190305-33
190305-22
190305-20
190304-31
190304-27
190304-26
190304-21
190304-16
190304-11
190304-07
190304-06
190303-40
190303-37
190303-36
190303-35
190303-30
190303-22
190302-20
190302-08
190301-29
190301-26
190301-23
190301-15
190301-1

# 结论
    11选5的1000期开奖结果数据中各种玩法的盈亏结果显示，高频彩11选5，亏多盈少，购彩请慎重！